[kafka]
    debug = true
    EnableAccessInterceptor = true
    EnableAccessInterceptorReq = true
    EnableAccessInterceptorRes = true
    brokers = ["localhost:9092"]
[kafka.client]
    timeout = "5s"
[kafka.producers.p1]        # 定义了名字为p1的producer
    topic = "comment-events"  # 指定生产消息的topic
[kafka.consumers.c1]        # 定义了名字为c1的consumer
    topic = "comment-events"  # 指定消费的topic
    groupID = "group-1"       # 如果配置了groupID，将初始化为consumerGroup
[kafkaConsumerServers.cs1]
    debug=true
    consumerName="c1"
[kafkaConsumerServers.s1]
    debug=true
    consumerName="c1"
[mongo.dev.comment]
	debug=true
	dsn="mongodb://root:password@127.0.0.1:27017/?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&ssl=false"

[redis.dev.comment]
    debug = true # mio增加redis debug，打开后可以看到，配置名、地址、耗时、请求数据、响应数据
    addr = "127.0.0.1:6379"
    enableAccessInterceptor = true
    enableAccessInterceptorReq = true
    enableAccessInterceptorRes = true