[mio.server.http]
    host = "0.0.0.0"
    port = 9003
[mio.client.directserver.user]
    address = "127.0.0.1:59001"
    balancerName = "round_robin" # 默认值
    enableBlock =  false # 默认值
    dialTimeout = "0s" # 默认值
    debug = true # 开启Debug信息
    enableTraceInterceptor = false # 链路追踪
    enableMetricInterceptor = true
    enableAccessInterceptor = true
    enableAccessInterceptorReq = true
    enableAccessInterceptorRes = true

[mio.client.directserver.comment]
    address = "127.0.0.1:59003"
    balancerName = "round_robin" # 默认值
    enableBlock =  false # 默认值
    dialTimeout = "0s" # 默认值
    debug = true # 开启Debug信息
    enableTraceInterceptor = false # 链路追踪
    enableMetricInterceptor = true
    enableAccessInterceptor = true
    enableAccessInterceptorReq = true
    enableAccessInterceptorRes = true
[kafka]
    debug = true
    EnableAccessInterceptor = true
    EnableAccessInterceptorReq = true
    EnableAccessInterceptorRes = true
    brokers = ["localhost:9092"]
[kafka.client]
    timeout = "5s"
[kafka.producers.p1]        # 定义了名字为p1的producer
    topic = "comment-events"  # 指定生产消息的topic
[mio.trace.jaeger]
    enableRPCMetrics = false
    [mio.trace.jaeger.sampler]
        type = "const"
        param = 0.001