run-domain-user :
	go run ./domain/user/cmd/main.go --config=./domain/user/cmd/config.toml

run-interface-feed:
	go run ./interface/feed/cmd/main.go --config=./interface/feed/cmd/config.toml
run-domain-feed:
	go run ./domain/feed/cmd/main.go --config=./domain/feed/cmd/config.toml

run-interface-comment:
	go run ./interface/comment/cmd/main.go --config=./interface/comment/cmd/config.toml
run-domain-comment :
	go run ./domain/comment/cmd/main.go --config=./domain/comment/cmd/config.toml
run-job-comment:
	go run ./job/comment/cmd/main.go --config=./job/comment/cmd/config.toml

run-domain-mall:
	go run ./domain/mall/cmd/main.go --config=./domain/mall/cmd/config.toml
run-interface-mall:
	go run ./interface/mall/cmd/main.go --config=./interface/mall/cmd/config.toml